spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: 
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8002
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/