<<<<<<< HEAD
=======
spring:
  application:
    name: docview-service
  profiles:
    active: dev
  cloud: 
    config:
      profile: ${spring.profiles.active}
      label: master
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server 
        
server:
  port: 8200
  
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8000/eureka/
>>>>>>> b2c2af189b7adc44134cffd796828379ac0a66bb
